"""empty message

Revision ID: 7a519e0ada45
Revises: 96408362b5e8
Create Date: 2026-03-03 18:52:27.572251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a519e0ada45'
down_revision = '96408362b5e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sales', ['sale_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sale_id')

    # ### end Alembic commands ###
